export enum Genre {
    ACTION = 'Action',
    ADVENTURE = 'Adventure',
    AUTOBIOGRAPHY = 'Autobiography',
    BIOGRAPHY = 'Biography',
    COMEDY = 'Comedy',
    CRIME = 'Crime',
    DRAMA = 'Drama',
    FANTASY = 'Fantasy',
    FICTION = 'Fiction',
    FOLKLORE = 'Folklore',
    FAIRY_TALE = 'Fairy Tale',
    HISTORY = 'History',
    HORROR = 'Horror',
    INFORMATIONAL = 'Informational',
    MYSTERY = 'Mystery',
    NON_FICTION = 'Non-Fiction',
    PHILOSOPHY = 'Philosophy',
    ROMANCE = 'Romance',
    RELIGION = 'Religion',
    SATIRE = 'Satire',
    SCIENCE_FICTION = 'Science Fiction',
    THRILLER = 'Thriller',
    TECHNOLOGY = 'Technology',
    WESTERN = 'Western',
    OTHER = 'Other',
    YOUNG_ADULT = 'Young Adult',
}